version: "3.9"

services:
  fireguard:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
    environment:
      - FLASK_SECRET_KEY=supersecret

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    volumes:
      - ./keycloak_exports:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME=158.39.75.130
    ports:
      - "5000:8080"
 
