version: "3.9"

services:
  fireguard:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
    environment:
      - FLASK_SECRET_KEY=supersecret

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_SPI_HOSTNAME_DEFAULT_SSL_REQUIRED=none
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  volumes:
    keycloak_data: